### ISSUE TITLE
.net standard support?

### ISSUE THREAD

**Issue by dweatherman** [unitycontainer/commonservicelocator#1]
Are there any plans to add .net standard API support anytime soon?

**Comment by hastarin** [comment]
Sadly I hadn't realized the project had moved here and had submitted a pull request for this on the old repository.

https://commonservicelocator.codeplex.com/SourceControl/network/forks/hastarin/netstandard/contribution/8979

I'll try to make time to add a similar pull request here.  Though a response from someone on the project so we know it's active might encourage me to spend the time.

**Comment by justinyoo** [comment]
I doubt this is to support .NET Standard anytime soon. Hence, I forked this repo and made some changes support .NET Standard. If you're interested in, use this NuGet package in the meantime:

https://www.nuget.org/packages/Aliencube.CommonServiceLocator/

**Comment by ENikS** [comment]
This issue is resolved in Release v1.4.0
