### ISSUE TITLE
Issues with latest 1.4.0

### ISSUE THREAD

**Issue by opcodewriter** [unitycontainer/commonservicelocator#10]
I updated by NuGet to 1.4.0, I am getting this error now:

![image](https://user-images.githubusercontent.com/15019084/31067718-f838fa5a-a75c-11e7-99fa-b20774b73797.png)

I tried to add redirect in app.config but it didn't work:

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.ServiceLocation" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4.0.0" newVersion="1.4.0.0" />
      </dependentAssembly>

However, one thing I noticed is the public token changed in 1.4.0.0, shouldn't it be the same like for 1.3.0.0?
![image](https://user-images.githubusercontent.com/15019084/31067784-5489b68c-a75d-11e7-9eee-08eb10921edc.png)

I am confused, what's the issue? Thanks!

**Comment by opcodewriter** [comment]
Another thing, CommonServiceLocator supports only .NETStandard 2? I can't use it in 1.6?

**Comment by ENikS** [comment]
``IServiceProvider`` is declared as:
```C#
public interface IServiceLocator : IServiceProvider
{
...
}
```
Unfortunately versions prior to NET Standard 2.0 do not supports ``IServiceProvider`` interface. It was reintroduced back in version 2.0.

**Comment by administersoftware** [comment]
Having same issue since upgrading to 1.4, downgrading back to 1.3 as I type but will keep an eye here in the hope of a speedy fix :)

**Comment by ENikS** [comment]
The original signing certificate is no longer available. 
I've upgraded version to 2.0.0 because of that.
