### ISSUE TITLE
NuGet 1.4 vs. 2.0 issues

### ISSUE THREAD

**Issue by vmelamed** [unitycontainer/commonservicelocator#11]
Hello,

Last night I saw that the v.1.4 is not downloadable anymore but 2.0 is available. I upgraded my solution to 2.0 and got messages like these:

```
The type 'ServiceLocatorImplBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'CommonServiceLocator, Version=1.4.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0'.
Cannot implicitly convert type 'Unity.UnityServiceLocator' to 'Microsoft.Practices.ServiceLocation.IServiceLocator'
```

Spent a lot of time trying to work out the problem but no luck. Any suggestions?
BTW I use Unity (now 5.0.0-beta), including Unity.SerfviceLocation. Can this be the problem (however Unity does not take explicit dependency on CSL)?

Thank you!

**Comment by ENikS** [comment]
Neither 1.4.0 nor 2.0.0 are direct replacements for 1.3.0. 
The signing certificate for 1.3.0 is lost so 1.4.0 and 2.0.0 are signed with different certificate and as far as Windows concerned are not compatible.

Unless you use Unity 5.0.0 you should not upgrade. It does not provide any new functionality.

**Comment by vmelamed** [comment]
ENikS, Thanks for the reply.

Yes, I did migrate Unity to 5.0.0 first with CSL 1.4. Then I tried upgrading CSL to 2.0.0 and this is when I started getting these weird messages. I did a lot of googling last night on them but nothing worked really. Do you have a third solution that uses Unity 5 and CSL 2 with no problems? Also is it possible that Unity takes a fixed dependency on CSL 1.4?

**Comment by ENikS** [comment]
Right. Unity is compiled with reference to 1.4.0. 

The 5.0.0 is still in very early stage of development. I'd wait until next beta 5.0.0-beta1 is out. I will disable 5.0.0-beta in NuGet to save people effort on integration with something that will be changing dramatically in next few weeks.

Sorry for your trouble

**Comment by vmelamed** [comment]
Thanks!
