### ISSUE TITLE
Error on updating Nuget package on PCL Project

### ISSUE THREAD

**Issue by hugodantas** [unitycontainer/commonservicelocator#13]
When I'm trying to update the Nuget package CommonServiceLocator from 1.3.0 to 2.0.1 on a PCL project in a Prism project, the Package Manager is throwing an error on output window:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'CommonServiceLocator 2.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

The package update successfully on Android and iOS projects, but in PCL i get this error

Visual Studio Enterprise 2017
Prism Template Pack 1.10
Unity Project

![image](https://user-images.githubusercontent.com/5769115/31581140-6cdd7c06-b139-11e7-876e-73a51e9d27ac.png)

**Comment by dationguyen** [comment]
+1 I got the same issue

**Comment by ENikS** [comment]
New CommonServiceLocator does not support PCL framework. 
PRISM is in process of updating adapter to use CommonServiceLocator 2 and Unity 5. [Here is associated discussion.](https://github.com/PrismLibrary/Prism/issues/1175)

**Comment by hugodantas** [comment]
Ok, ENikS!
Understood!

I'll close the issue according to your answer.

For everyone who'll see this issue in future:
There's no need to update the CommonServiceLocator Nuget package from 1.3.0 to 2.0.1.
