### ISSUE TITLE
Support Profile259 

### ISSUE THREAD

**Issue by dationguyen** [unitycontainer/commonservicelocator#15]
Hi Guys, 
I am currently working with Xamarin.Form + Prism + Unity 
I tried to upgrade commonservicelocator from 1.3.0 to 2.0.1 but i received this message : 
Could not install package 'CommonServiceLocator 2.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am wondering if this update support xamarin.form or not. 

Hope to hear from you soon,
Best regards,
Dat Nguyen

**Comment by ENikS** [comment]
I am afraid we can not help you with it. Visual Studio 2017 no longer supports NetPortable framework. 

Thinking about it, nothing stops you from grabbing the code and just creating and signing local assembly. It would be as good as what we would distribute and when you upgrade to latest framework (Core or Standard) you could switch back to using official packages.
