### ISSUE TITLE
Failing build when using ILMerge

### ISSUE THREAD

**Issue by lkavale** [unitycontainer/commonservicelocator#16]
Hi, I have CommonServiceLocator 2.0.1 in my .net 4.6.2 project. Iam using ILMerge 2.14.1208 and I getting this error.

ILMerge.Merge: 	There were errors reported in CommonServiceLocator's metadata.
Exception of type 'System.OutOfMemoryException' was thrown.

Probably there were currupted pdb file distributed by Nuget.

**Comment by ENikS** [comment]
Probably or they are indeed corrupted? 
I see nothing wrong with them. Could you provide more info?

**Comment by lkavale** [comment]
Probably, when I want use pdb as is, its ok. But ILMerge cannot merge pdb files with others, that ends with error.

ILMerge.Merge: There were errors reported in CommonServiceLocator's metadata.
Exception of type 'System.OutOfMemoryException' was thrown.

When I disable debugging in ILMerge, the merge result is created, but the application not working. But when I disable debugging is hard to find other problems, (not merged app running propely of course).

**Comment by ENikS** [comment]
I would assume this is side effect of C# 7.x and ILMerge.Merge not supporting it properly. I would create issue at [ILMerge.Merge](https://github.com/Microsoft/ILMerge) repo and see if they can help you.
