### ISSUE TITLE
error installing 2.0.1

### ISSUE THREAD

**Issue by tele-bird** [unitycontainer/commonservicelocator#17]
When I attempt to upgrade from 1.3.0, I get this error:

Could not install package 'CommonServiceLocator 2.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

After some investigation, I found it may be an issue with the package, like this case: https://forums.xamarin.com/discussion/80045/error-using-nuget

**Comment by ENikS** [comment]
Microsoft kind of abandoned support for PCL in VS2017. It is now supported through NetStandard2.0 if I am not mistaking. I don't even see an option to select that profile in new Visual Studio.

Are you upgrading it as part of Unity Container or standalone?

**Comment by tele-bird** [comment]
Standalone.  Thanks, that explains why I saw it in the Unity package!
