### ISSUE TITLE
Rename IsLocationProviderSet to IsLocatorProviderSet in ServiceLocator class

### ISSUE THREAD

**Issue by krispenner** [unitycontainer/commonservicelocator#19]
Probably just an accidental oversight but would be nice to have this named correctly to match the property/method it relates to.

Rename from: ServiceLocator.IsLocat**ion**ProviderSet
Rename to: ServiceLocator.IsLocat**or**ProviderSet

**Comment by ENikS** [comment]
Would you like to send a Pull Request for that?

**Comment by ENikS** [comment]
I guess not

**Comment by krispenner** [comment]
Created a pull request, not sure if there is a standard procedure to follow, have not submitted a pull request before.
