### ISSUE TITLE
CommonServiceLocator.pdb Error during TFS build

### ISSUE THREAD

**Issue by totollygeek** [unitycontainer/commonservicelocator#23]
We started using Unity NuGet package in our system, that comes with the latest version of CommonServiceLocator. Since that every TFS nightly build is failing with the following error:

Indexed source information could not be retrieved from C:\...\bin\Release\CommonServiceLocator.pdb. Error: Symbol indexes could not be retrieved.

Any idea if that is a bug or we are doing it wrong?

**Comment by ENikS** [comment]
No idea. Perhaps if you provide more info...

**Comment by mcfreder75** [comment]
I hit this issue the same day that you did.  After some research on other forums I found that you should not commit pdb files for 3rd party assemblies.  This creates potential for the problem above.  I removed the pdb files contained in the Unity package folder from our source control and the build server was successful in building.

Hope this helps.

**Comment by totollygeek** [comment]
Removing the pdb files from the build actually seemed like the most meaningful solution. And it worked. Thanks a lot @mcfreder75 !
