### ISSUE TITLE
Class CommonServiceLocator.Constants in the public namespace

### ISSUE THREAD

**Issue by Xarlot** [unitycontainer/commonservicelocator#24]
After migrating my project from 1.3 to 2.0.4 the CommonServiceLocator.Constants class generates the tons of conflicts with my class Constants. 
Why do you add this class in the CommonServiceLocator namespace? I think will be better to hide this helper class somewhere to avoid conflicts.

**Comment by ENikS** [comment]
It would not generate any conflicts unless you use Unity namespace. Do you use Unity.* namespace in your local projects?
