### ISSUE TITLE
Add libraries for each framework kind - issue with types not referenced

### ISSUE THREAD

**Issue by evgeni84** [unitycontainer/commonservicelocator#3]
Hi

Please add for each framework type a separate assembly, instead of using PCL library, as the current approach is not recommended by Microsoft, see https://docs.microsoft.com/en-us/nuget/schema/target-frameworks#portable-class-libraries, and causes exceptions like 
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f
5f7f11d50a3a'.
error CS0012: The type 'System.ComponentModel.INotifyPropertyChanged' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, C
ulture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

due to the fact, that the commonservicelocator references different mscorlib/System.ObjectModel version.

It has an impact on generating xml serializer assemblies, for speeding up 64 bit applications.

See also 
https://stackoverflow.com/questions/27841167/the-type-system-componentmodel-inotifypropertychanged-is-defined-in-an-assembl

**Comment by ENikS** [comment]
This issue is resolved in Release v1.4.0
