### ISSUE TITLE
ServiceLocator error CS0433: The type 'ServiceLocator' exists in both 'CommonServiceLocator...

### ISSUE THREAD

**Issue by nasheayahu** [unitycontainer/commonservicelocator#6]
Hi, I don't know where I can get help with this, so I hoping either you can direct me to the correct place or show me a solution.  Just started a new 4.7 WPF project using MEF and updated to the 1.4.0 and I get this Exception:

>ServiceLocator error CS0433: The type 'ServiceLocator' exists in both 'CommonServiceLocator, Version=1.4.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' and 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

when doing this here in the MefBootstrapper:

```
protected override RegionAdapterMappings ConfigureRegionAdapterMappings()
{
	RegionAdapterMappings regionAdapterMappings = base.ConfigureRegionAdapterMappings();

	if (regionAdapterMappings != null)
	{
		IRegionBehaviorFactory factory = ServiceLocator.Current.GetInstance<IRegionBehaviorFactory>();
		regionAdapterMappings.RegisterMapping(typeof(DockingManager), new DockingManagerRegionAdapter(factory));
	}

	return regionAdapterMappings;
}

protected override IRegionBehaviorFactory ConfigureDefaultRegionBehaviors()
{
	IRegionBehaviorFactory factory = base.ConfigureDefaultRegionBehaviors();
	return factory;
}

```

So, I'm assuming I just can't use version 4.7 for MEF?

Thanks!...

**Comment by nasheayahu** [comment]
Oh, one other question, why didn't the update remove the 1.3.0 version, is this a Nuget bug for VS 2017?

**Comment by ENikS** [comment]
If you are using Unity 4 you should use ServiceLocator 1.3

**Comment by nasheayahu** [comment]
Okay, thanks ENikS, I will just stay with 1.3.0 for MEF also...

**Comment by ENikS** [comment]
These are not mutually exclusive so VS will not remove one if other exists.

**Comment by nasheayahu** [comment]
You know, I was not paying attention to what the update was for:

![screenshot 17](https://user-images.githubusercontent.com/5845052/30674683-03be2de6-9e39-11e7-97d3-4cdb3746f6dc.png)

Unity only..., is it ok to delete this thread, not needed since I was not paying attention?

**Comment by ENikS** [comment]
I closed it
