### ISSUE TITLE
New Version 1.4.0 does not compile in Xamarin.Android project

### ISSUE THREAD

**Issue by bergmeister** [unitycontainer/commonservicelocator#9]
I tried upgrading from 1.3.0 to 1.4.0 in a Xamarin/Android solution that uses .Net Standard 2.0 and experience the following compilation error in the Xamarin.Android project:

```
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Microsoft.Practices.ServiceLocation.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	MyAppName.Xamarin.Android			
```

I am using the latest (stable) version of all my components, including Visual Studio 2017, Xamarin.Forms, Unity, .Net Standard 2.0, etc.
The Android project is targeting Android 7.1 (i.e. API 25).
Note that due to [this](https://bugzilla.xamarin.com/show_bug.cgi?id=59313) bug in Xamarin/MSBuild I have to add the NuGet package to both the Xamarin .Net Standard 2.0 BCL project and the Android project.

**Comment by ENikS** [comment]
Something in your solution trying to load old version of the assembly. You need to add binary redirect into your app.config file (or whatever Xamarin is using for that purpose). 
Here [some documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions) on the subject.

**Comment by wowfood** [comment]
It seems this is happening with other things too.  Same issue (i believe) is popping up in MVVM-Light, and in Prism projects.

**Comment by ENikS** [comment]
Yes, you need redirect for all of them. You could set it at machine level so it will work for all of them.
